export const mockFeedData = [
  {
    id: 'security_compliance_audit_v4.md',
    title: 'security_compliance_audit_v4.md',
    source: 'GITHUB_REPO',
    path: '/docs/security/',
    statusText: 'VECTORIZING_84%',
    statusClass: 'text-accent',
    progress: 84,
    progressClass: 'bg-accent shadow-[0_0_10px_#00f2ff]',
    estTime: '4s',
    date: '2024-05-20 14:22:01.004',
    icon: 'description',
    iconClass: 'text-accent border-accent/20 bg-accent/5',
    actions: ['RE-INDEX', 'VIEW_SOURCE', 'TRUNCATE'],
    cardClass: 'group',
  },
  {
    id: 'api_v2_endpoint_mapping.json',
    title: 'api_v2_endpoint_mapping.json',
    source: 'INTERNAL_STORAGE',
    path: '/meta/schemas/',
    statusText: 'COMPLETE_100%',
    statusClass: 'text-terminal-green',
    progress: 100,
    progressClass: 'bg-terminal-green shadow-[0_0_8px_#00ff41]',
    date: '2024-05-20 13:45:12.882',
    icon: 'schema',
    iconClass: 'text-slate-400 border-white/10 bg-white/5',
    actions: ['RE-INDEX', 'VIEW_SOURCE'],
    cardClass: 'opacity-80 hover:opacity-100',
    titleClass: 'text-slate-300',
  },
  {
    id: 'community_feedback_stream.xlsx',
    title: 'community_feedback_stream.xlsx',
    source: 'CRM_WEBHOOK',
    error: 'INVALID_FORMAT',
    statusText: 'FAILED_0%',
    statusClass: 'text-red-500',
    progress: 0,
    progressBgClass: 'bg-red-900/20',
    date: '2024-05-20 12:10:55.001',
    icon: 'error',
    iconClass: 'text-red-500 border-red-500/20 bg-red-500/10',
    actions: [
      { label: 'RETRY_INGESTION', className: '!text-red-400 !border-red-900/50 hover:!bg-red-500/20' },
      { label: 'LOG_DETAILS' }
    ],
    cardClass: 'border-red-900/30 bg-red-950/5',
  },
  {
    id: 'sdk_ref_v1.2.md',
    title: 'sdk_ref_v1.2.md',
    queueStatus: 'WAITING_IN_QUEUE // POSITION: 01',
    statusText: 'PENDING',
    statusClass: 'text-slate-600',
    progress: 0,
    progressBgClass: 'opacity-20',
    date: 'PENDING_SYNC',
    icon: 'hourglass_empty',
    iconClass: 'text-slate-500 border-white/10 bg-white/5',
    actions: ['PRIORITIZE', 'REMOVE'],
    cardClass: 'opacity-50',
    titleClass: 'text-slate-500',
    dateClass: 'text-slate-700',
  }
];
